-- Questline — Phase 0 core schema.
-- 6 core tables only: users, goals, milestones, tasks, activity_days, streaks.
-- topics / ai_jobs / ai_messages / achievements arrive in their own Phase 1+ migrations.
-- UUID primary keys are generated by the application (Hibernate), so no DB default is needed.

create table users (
    id                     uuid         primary key,
    email                  varchar(255) not null unique,
    name                   varchar(255),
    image                  varchar(1024),
    timezone               varchar(64)  not null default 'Europe/Kyiv',
    daily_capacity_minutes integer      not null default 120,
    daily_task_goal        integer      not null default 1,
    xp_total               bigint       not null default 0,
    created_at             timestamptz,
    updated_at             timestamptz
);

create table goals (
    id          uuid         primary key,
    user_id     uuid         not null references users (id),
    title       varchar(255) not null,
    description text,
    context     text,
    target      text,
    source      varchar(32)  not null default 'AI_GENERATED',
    target_date date,
    status      varchar(32)  not null default 'ACTIVE',
    progress    double precision not null default 0,
    created_at  timestamptz,
    updated_at  timestamptz
);
create index idx_goals_user on goals (user_id);

create table milestones (
    id          uuid         primary key,
    goal_id     uuid         not null references goals (id) on delete cascade,
    title       varchar(255) not null,
    description text,
    order_index integer      not null default 0,
    status      varchar(32)  not null default 'NOT_STARTED',
    progress    double precision not null default 0,
    target_date date
);
create index idx_milestones_goal on milestones (goal_id);

create table tasks (
    id              uuid         primary key,
    user_id         uuid         not null references users (id),
    goal_id         uuid         not null references goals (id) on delete cascade,
    milestone_id    uuid         references milestones (id) on delete cascade,
    parent_task_id  uuid         references tasks (id) on delete cascade,
    title           varchar(255) not null,
    description     text,
    estimate_minutes integer,
    order_index     integer      not null default 0,
    status          varchar(32)  not null default 'TODO',
    scheduled_for   date,
    completed_at    timestamptz,
    resources       jsonb,
    notes           text,
    created_at      timestamptz,
    updated_at      timestamptz
);
create index idx_tasks_user_scheduled on tasks (user_id, scheduled_for);
create index idx_tasks_milestone_order on tasks (milestone_id, order_index);

create table activity_days (
    id              uuid    primary key,
    user_id         uuid    not null references users (id),
    date            date    not null,
    tasks_completed integer not null default 0,
    minutes_spent   integer not null default 0,
    xp_earned       integer not null default 0,
    goal_met        boolean not null default false,
    constraint uq_activity_days_user_date unique (user_id, date)
);

create table streaks (
    user_id           uuid    primary key references users (id),
    current           integer not null default 0,
    longest           integer not null default 0,
    last_active_date  date,
    freezes_available integer not null default 0,
    updated_at        timestamptz
);
